# Generated by Django 4.2.7 on 2026-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
