# Generated by Django 4.2.7 on 2026-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coverage_end',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
