# Generated by Django 4.2.7 on 2026-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_status_alter_pet_coverage_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active')], default='PENDING', max_length=10),
        ),
    ]
